[2025-04-18T00:07:05.567+0000] {taskinstance.py:1094} DEBUG - previous_execution_date was called
[2025-04-18T00:07:05.619+0000] {__init__.py:51} DEBUG - Loading core task runner: StandardTaskRunner
[2025-04-18T00:07:05.669+0000] {taskinstance.py:1094} DEBUG - previous_execution_date was called
[2025-04-18T00:07:05.679+0000] {base_task_runner.py:68} DEBUG - Planning to run as the  user
[2025-04-18T00:07:05.686+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: parquet_loader.create_staging_table scheduled__2025-04-17T23:25:00+00:00 [queued]> from DB
[2025-04-18T00:07:06.104+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_loader.create_staging_table scheduled__2025-04-17T23:25:00+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-04-18T00:07:06.104+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_loader.create_staging_table scheduled__2025-04-17T23:25:00+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-04-18T00:07:06.116+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_loader.create_staging_table scheduled__2025-04-17T23:25:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-04-18T00:07:06.117+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_loader.create_staging_table scheduled__2025-04-17T23:25:00+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2025-04-18T00:07:06.117+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_loader.create_staging_table scheduled__2025-04-17T23:25:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-04-18T00:07:06.118+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parquet_loader.create_staging_table scheduled__2025-04-17T23:25:00+00:00 [queued]>
[2025-04-18T00:07:06.121+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_loader.create_staging_table scheduled__2025-04-17T23:25:00+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-04-18T00:07:06.122+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_loader.create_staging_table scheduled__2025-04-17T23:25:00+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-04-18T00:07:06.122+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_loader.create_staging_table scheduled__2025-04-17T23:25:00+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2025-04-18T00:07:06.126+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_loader.create_staging_table scheduled__2025-04-17T23:25:00+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-04-18T00:07:06.134+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_loader.create_staging_table scheduled__2025-04-17T23:25:00+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-04-18T00:07:06.135+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parquet_loader.create_staging_table scheduled__2025-04-17T23:25:00+00:00 [queued]>
[2025-04-18T00:07:06.136+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-04-18T00:07:06.161+0000] {taskinstance.py:1382} INFO - Executing <Task(SQLExecuteQueryOperator): create_staging_table> on 2025-04-17 23:25:00+00:00
[2025-04-18T00:07:06.167+0000] {standard_task_runner.py:57} INFO - Started process 250 to run task
[2025-04-18T00:07:06.175+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'parquet_loader', 'create_staging_table', 'scheduled__2025-04-17T23:25:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/parquet_to_postgres_dbt.py', '--cfg-path', '/tmp/tmpcs2dqtju']
[2025-04-18T00:07:06.186+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask create_staging_table
[2025-04-18T00:07:06.189+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0xffff90033af0>]
[2025-04-18T00:07:06.422+0000] {taskinstance.py:1094} DEBUG - previous_execution_date was called
[2025-04-18T00:07:06.435+0000] {task_command.py:416} INFO - Running <TaskInstance: parquet_loader.create_staging_table scheduled__2025-04-17T23:25:00+00:00 [running]> on host 5c2de455146a
[2025-04-18T00:07:06.435+0000] {settings.py:351} DEBUG - Disposing DB connection pool (PID 250)
[2025-04-18T00:07:06.436+0000] {settings.py:210} DEBUG - Setting up DB connection pool (PID 250)
[2025-04-18T00:07:06.438+0000] {settings.py:283} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-04-18T00:07:06.443+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: parquet_loader.create_staging_table scheduled__2025-04-17T23:25:00+00:00 [running]> from DB
[2025-04-18T00:07:06.558+0000] {taskinstance.py:1094} DEBUG - previous_execution_date was called
[2025-04-18T00:07:06.561+0000] {taskinstance.py:925} DEBUG - Clearing XCom data
[2025-04-18T00:07:06.577+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-04-18T00:07:06.638+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-04-18T00:07:06.680+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='parquet_loader' AIRFLOW_CTX_TASK_ID='create_staging_table' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T23:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-17T23:25:00+00:00'
[2025-04-18T00:07:06.680+0000] {__init__.py:116} DEBUG - Preparing lineage inlets and outlets
[2025-04-18T00:07:06.681+0000] {__init__.py:157} DEBUG - inlets: [], outlets: []
[2025-04-18T00:07:06.682+0000] {sql.py:274} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS staging_table (
        id INT,
        name TEXT,
        age INT
    );
    
[2025-04-18T00:07:06.683+0000] {sql.py:147} DEBUG - Get connection for postgres_default
[2025-04-18T00:07:06.714+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-18T00:07:06.715+0000] {providers_manager.py:366} DEBUG - Initializing Providers Manager[hooks]
[2025-04-18T00:07:06.716+0000] {providers_manager.py:369} DEBUG - Initialization of Providers Manager[hooks] took 0.00 seconds
[2025-04-18T00:07:06.719+0000] {sql.py:381} DEBUG - Executing following statements against DB: ['\n        CREATE TABLE IF NOT EXISTS staging_table (\n        id INT,\n        name TEXT,\n        age INT\n    );\n    ']
[2025-04-18T00:07:06.745+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-18T00:07:06.758+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[2025-04-18T00:07:06.761+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: parquet_loader.create_staging_table scheduled__2025-04-17T23:25:00+00:00 [running]> from DB
[2025-04-18T00:07:06.958+0000] {taskinstance.py:2430} DEBUG - Task Duration set to 0.839066
[2025-04-18T00:07:06.984+0000] {taskinstance.py:1458} DEBUG - Clearing next_method and next_kwargs.
[2025-04-18T00:07:06.991+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=parquet_loader, task_id=create_staging_table, execution_date=20250417T232500, start_date=20250418T000706, end_date=20250418T000706
[2025-04-18T00:07:07.109+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2025-04-18T00:07:07.113+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 43 for task create_staging_table (connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"
; 250)
[2025-04-18T00:07:07.188+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-18T00:07:07.330+0000] {dagrun.py:734} DEBUG - number of tis tasks for <DagRun parquet_loader @ 2025-04-17 23:25:00+00:00: scheduled__2025-04-17T23:25:00+00:00, state:running, queued_at: 2025-04-17 23:30:00.986769+00:00. externally triggered: False>: 8 task(s)
[2025-04-18T00:07:07.331+0000] {dagrun.py:755} DEBUG - number of scheduleable tasks for <DagRun parquet_loader @ 2025-04-17 23:25:00+00:00: scheduled__2025-04-17T23:25:00+00:00, state:running, queued_at: 2025-04-17 23:30:00.986769+00:00. externally triggered: False>: 3 task(s)
[2025-04-18T00:07:07.332+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_loader.create_main_table scheduled__2025-04-17T23:25:00+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-04-18T00:07:07.333+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_loader.create_main_table scheduled__2025-04-17T23:25:00+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-04-18T00:07:07.335+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_loader.create_main_table scheduled__2025-04-17T23:25:00+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'create_staging_table'}
[2025-04-18T00:07:07.336+0000] {taskinstance.py:1149} DEBUG - Dependencies not met for <TaskInstance: parquet_loader.create_main_table scheduled__2025-04-17T23:25:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'create_staging_table'}
[2025-04-18T00:07:07.337+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_loader.load_csv_to_postgres scheduled__2025-04-17T23:25:00+00:00 [up_for_retry]> dependency 'Not In Retry Period' PASSED: False, Task is not ready for retry yet but will be retried automatically. Current date is 2025-04-18T00:07:07.337865+00:00 and task will be retried at 2025-04-18T00:12:06.744783+00:00.
[2025-04-18T00:07:07.339+0000] {taskinstance.py:1149} DEBUG - Dependencies not met for <TaskInstance: parquet_loader.load_csv_to_postgres scheduled__2025-04-17T23:25:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2025-04-18T00:07:07.337865+00:00 and task will be retried at 2025-04-18T00:12:06.744783+00:00.
[2025-04-18T00:07:07.341+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_loader.load_csv_to_postgres scheduled__2025-04-17T23:25:00+00:00 [up_for_retry]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-04-18T00:07:07.344+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_loader.create_staging_table scheduled__2025-04-17T23:25:00+00:00 [up_for_retry]> dependency 'Not In Retry Period' PASSED: False, Task is not ready for retry yet but will be retried automatically. Current date is 2025-04-18T00:07:07.344221+00:00 and task will be retried at 2025-04-18T00:12:06.958091+00:00.
[2025-04-18T00:07:07.358+0000] {taskinstance.py:1149} DEBUG - Dependencies not met for <TaskInstance: parquet_loader.create_staging_table scheduled__2025-04-17T23:25:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2025-04-18T00:07:07.344221+00:00 and task will be retried at 2025-04-18T00:12:06.958091+00:00.
[2025-04-18T00:07:07.359+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_loader.create_staging_table scheduled__2025-04-17T23:25:00+00:00 [up_for_retry]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-04-18T00:07:07.359+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_loader.create_staging_table scheduled__2025-04-17T23:25:00+00:00 [up_for_retry]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2025-04-18T00:07:07.376+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
