[2025-04-18T00:22:26.894+0000] {taskinstance.py:1094} DEBUG - previous_execution_date was called
[2025-04-18T00:22:26.906+0000] {__init__.py:51} DEBUG - Loading core task runner: StandardTaskRunner
[2025-04-18T00:22:26.919+0000] {taskinstance.py:1094} DEBUG - previous_execution_date was called
[2025-04-18T00:22:26.921+0000] {base_task_runner.py:68} DEBUG - Planning to run as the  user
[2025-04-18T00:22:26.926+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres manual__2025-04-18T00:22:05.188674+00:00 [queued]> from DB
[2025-04-18T00:22:27.049+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres manual__2025-04-18T00:22:05.188674+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-04-18T00:22:27.049+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres manual__2025-04-18T00:22:05.188674+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-04-18T00:22:27.050+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres manual__2025-04-18T00:22:05.188674+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-04-18T00:22:27.055+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres manual__2025-04-18T00:22:05.188674+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-04-18T00:22:27.056+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres manual__2025-04-18T00:22:05.188674+00:00 [queued]>
[2025-04-18T00:22:27.056+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres manual__2025-04-18T00:22:05.188674+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-04-18T00:22:27.056+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres manual__2025-04-18T00:22:05.188674+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-04-18T00:22:27.062+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres manual__2025-04-18T00:22:05.188674+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-04-18T00:22:27.062+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres manual__2025-04-18T00:22:05.188674+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-04-18T00:22:27.064+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres manual__2025-04-18T00:22:05.188674+00:00 [queued]>
[2025-04-18T00:22:27.064+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-04-18T00:22:27.074+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_csv_to_postgres> on 2025-04-18 00:22:05.188674+00:00
[2025-04-18T00:22:27.078+0000] {standard_task_runner.py:57} INFO - Started process 268 to run task
[2025-04-18T00:22:27.080+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'parquet_to_csv_to_postgres_loader', 'load_csv_to_postgres', 'manual__2025-04-18T00:22:05.188674+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/parquet_to_postgres_dbt.py', '--cfg-path', '/tmp/tmpcr51aefp']
[2025-04-18T00:22:27.082+0000] {standard_task_runner.py:85} INFO - Job 65: Subtask load_csv_to_postgres
[2025-04-18T00:22:27.083+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0xffff9bb8eaf0>]
[2025-04-18T00:22:27.129+0000] {taskinstance.py:1094} DEBUG - previous_execution_date was called
[2025-04-18T00:22:27.131+0000] {task_command.py:416} INFO - Running <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres manual__2025-04-18T00:22:05.188674+00:00 [running]> on host a9ba873147a3
[2025-04-18T00:22:27.131+0000] {settings.py:351} DEBUG - Disposing DB connection pool (PID 268)
[2025-04-18T00:22:27.132+0000] {settings.py:210} DEBUG - Setting up DB connection pool (PID 268)
[2025-04-18T00:22:27.132+0000] {settings.py:283} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-04-18T00:22:27.133+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres manual__2025-04-18T00:22:05.188674+00:00 [running]> from DB
[2025-04-18T00:22:27.168+0000] {taskinstance.py:1094} DEBUG - previous_execution_date was called
[2025-04-18T00:22:27.169+0000] {taskinstance.py:925} DEBUG - Clearing XCom data
[2025-04-18T00:22:27.175+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-04-18T00:22:27.196+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-04-18T00:22:27.209+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='parquet_to_csv_to_postgres_loader' AIRFLOW_CTX_TASK_ID='load_csv_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T00:22:05.188674+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T00:22:05.188674+00:00'
[2025-04-18T00:22:27.209+0000] {__init__.py:116} DEBUG - Preparing lineage inlets and outlets
[2025-04-18T00:22:27.209+0000] {__init__.py:157} DEBUG - inlets: [], outlets: []
[2025-04-18T00:22:27.224+0000] {logging_mixin.py:151} INFO - Error loading house-price.csv: extra data after last expected column
CONTEXT:  COPY temp_import, line 2: "13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished"
[2025-04-18T00:22:27.224+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/parquet_to_postgres_dbt.py", line 55, in load_csv_to_postgres
    cur.copy_expert(
psycopg2.errors.BadCopyFileFormat: extra data after last expected column
CONTEXT:  COPY temp_import, line 2: "13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished"

[2025-04-18T00:22:27.226+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: parquet_to_csv_to_postgres_loader.load_csv_to_postgres manual__2025-04-18T00:22:05.188674+00:00 [running]> from DB
[2025-04-18T00:22:27.235+0000] {taskinstance.py:2430} DEBUG - Task Duration set to 0.179523
[2025-04-18T00:22:27.236+0000] {taskinstance.py:1458} DEBUG - Clearing next_method and next_kwargs.
[2025-04-18T00:22:27.237+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=parquet_to_csv_to_postgres_loader, task_id=load_csv_to_postgres, execution_date=20250418T002205, start_date=20250418T002227, end_date=20250418T002227
[2025-04-18T00:22:27.246+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2025-04-18T00:22:27.246+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 65 for task load_csv_to_postgres (extra data after last expected column
CONTEXT:  COPY temp_import, line 2: "13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished"
; 268)
[2025-04-18T00:22:27.260+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-18T00:22:27.278+0000] {dagrun.py:734} DEBUG - number of tis tasks for <DagRun parquet_to_csv_to_postgres_loader @ 2025-04-18 00:22:05.188674+00:00: manual__2025-04-18T00:22:05.188674+00:00, state:running, queued_at: 2025-04-18 00:22:05.209758+00:00. externally triggered: True>: 0 task(s)
[2025-04-18T00:22:27.279+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
