[2025-04-18T00:03:15.309+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fixed_parquet_loader.create_staging_table scheduled__2025-04-17T23:55:00+00:00 [queued]>
[2025-04-18T00:03:15.315+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fixed_parquet_loader.create_staging_table scheduled__2025-04-17T23:55:00+00:00 [queued]>
[2025-04-18T00:03:15.315+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-04-18T00:03:15.325+0000] {taskinstance.py:1382} INFO - Executing <Task(SQLExecuteQueryOperator): create_staging_table> on 2025-04-17 23:55:00+00:00
[2025-04-18T00:03:15.329+0000] {standard_task_runner.py:57} INFO - Started process 258 to run task
[2025-04-18T00:03:15.332+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fixed_parquet_loader', 'create_staging_table', 'scheduled__2025-04-17T23:55:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/parquet_to_postgres_dbt.py', '--cfg-path', '/tmp/tmp2bu8un34']
[2025-04-18T00:03:15.335+0000] {standard_task_runner.py:85} INFO - Job 39: Subtask create_staging_table
[2025-04-18T00:03:15.389+0000] {task_command.py:416} INFO - Running <TaskInstance: fixed_parquet_loader.create_staging_table scheduled__2025-04-17T23:55:00+00:00 [running]> on host e27c32911ad1
[2025-04-18T00:03:15.467+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fixed_parquet_loader' AIRFLOW_CTX_TASK_ID='create_staging_table' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T23:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-17T23:55:00+00:00'
[2025-04-18T00:03:15.468+0000] {sql.py:274} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS staging_table (
        id INT,
        name TEXT,
        age INT
    );
    
[2025-04-18T00:03:15.478+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-18T00:03:15.489+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-04-18T00:03:15.494+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[2025-04-18T00:03:15.505+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=fixed_parquet_loader, task_id=create_staging_table, execution_date=20250417T235500, start_date=20250418T000315, end_date=20250418T000315
[2025-04-18T00:03:15.516+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 39 for task create_staging_table (connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"
; 258)
[2025-04-18T00:03:15.556+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-18T00:03:15.578+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
