[2025-04-17T23:28:20.393+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parquet_loader.load_parquet_to_postgres scheduled__2025-04-17T23:20:00+00:00 [queued]>
[2025-04-17T23:28:20.400+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parquet_loader.load_parquet_to_postgres scheduled__2025-04-17T23:20:00+00:00 [queued]>
[2025-04-17T23:28:20.400+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-04-17T23:28:20.410+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_parquet_to_postgres> on 2025-04-17 23:20:00+00:00
[2025-04-17T23:28:20.413+0000] {standard_task_runner.py:57} INFO - Started process 224 to run task
[2025-04-17T23:28:20.417+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'parquet_loader', 'load_parquet_to_postgres', 'scheduled__2025-04-17T23:20:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/parquet_to_postgres_dbt.py', '--cfg-path', '/tmp/tmpzb40cq1k']
[2025-04-17T23:28:20.421+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask load_parquet_to_postgres
[2025-04-17T23:28:20.485+0000] {task_command.py:416} INFO - Running <TaskInstance: parquet_loader.load_parquet_to_postgres scheduled__2025-04-17T23:20:00+00:00 [running]> on host fe2f3e6bd690
[2025-04-17T23:28:20.579+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='parquet_loader' AIRFLOW_CTX_TASK_ID='load_parquet_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T23:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-17T23:20:00+00:00'
[2025-04-17T23:28:20.678+0000] {logging_mixin.py:151} WARNING - /opt/airflow/dags/parquet_to_postgres_dbt.py:28 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-04-17T23:28:20.681+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/parquet_to_postgres_dbt.py", line 28, in process_parquet
    df.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 769, in to_sql
    return pandas_sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 2378, in to_sql
    table.create()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 903, in create
    if self.exists():
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 889, in exists
    return self.pd_sql.has_table(self.name, self.schema)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 2385, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 2200, in execute
    cur = self.con.cursor()
AttributeError: 'dict' object has no attribute 'cursor'
[2025-04-17T23:28:20.695+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=parquet_loader, task_id=load_parquet_to_postgres, execution_date=20250417T232000, start_date=20250417T232820, end_date=20250417T232820
[2025-04-17T23:28:20.705+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task load_parquet_to_postgres ('dict' object has no attribute 'cursor'; 224)
[2025-04-17T23:28:20.721+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-17T23:28:20.771+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
